server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/student?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&sessionVariables=character_set_client=utf8mb4,character_set_connection=utf8mb4,character_set_results=utf8mb4&allowPublicKeyRetrieval=true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:shatou5114}
spring.datasource.hikari.data-source-properties.useGeneratedKeys=true
spring.datasource.hikari.data-source-properties.keyColumn=id

spring.jpa.show-sql=true

debug=true
logging.level.org.apache.ibatis=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.com.example.mapper=DEBUG
logging.level.org.example.dao=DEBUG
logging.level.org.apache.ibatis.builder.xml=DEBUG
logging.level.org.example.service.impl.AiMedicalQaServiceImpl=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
